FROM debian:trixie-slim AS base
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && rm -rf /var/lib/apt/lists/*

FROM base AS builder
COPY --from=docker.io/astral/uv:latest /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_PROJECT_ENVIRONMENT=${VIRTUAL_ENV}
ENV UV_PYTHON_INSTALL_DIR=/opt/share/python

RUN uv venv ${VIRTUAL_ENV} --python=3.12
RUN uv run python -m compileall ${UV_PYTHON_INSTALL_DIR}
RUN uv pip install --pre flyte

FROM base AS runner
COPY --from=builder /opt/share/python /opt/share/python
COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
