from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path
from typing import Collection, List, Optional, Type

import libcst as cst
import libcst.matchers as m

from ._analyze import analyze
from ._context import MigrationContext
from ._cst import Rule, todo_comment
from ._imports import finalize_imports
from ._result import TODO_MARKER, MigrationError, MigrationResult, Todo
from ._rules import SELECTABLE_RULES, LeftoversRule

GENERATED_MARKER = "# Generated by `flyte migrate`"
RULE_IDS = [rule.id for rule in SELECTABLE_RULES]


def output_path_for(source_path: Path, suffix: str = "_v2") -> Path:
    """`pipeline.py` -> `pipeline_v2.py`. The suffix keeps the output importable as a Python module."""
    if not re.fullmatch(r"[A-Za-z0-9_]+", suffix):
        raise MigrationError(
            f"Invalid suffix {suffix!r}: use letters, digits and underscores so the output is importable."
        )
    return source_path.with_name(f"{source_path.stem}{suffix}{source_path.suffix}")


def select_rules(rules: Optional[Collection[str]] = None, exclude_rules: Collection[str] = ()) -> List[Type[Rule]]:
    unknown = sorted((set(rules or ()) | set(exclude_rules)) - set(RULE_IDS))
    if unknown:
        raise MigrationError(f"Unknown rule(s): {', '.join(unknown)}. Valid rules: {', '.join(RULE_IDS)}.")
    return [r for r in SELECTABLE_RULES if (rules is None or r.id in rules) and r.id not in exclude_rules]


def migrate_file(
    source_path: Path,
    *,
    suffix: str = "_v2",
    rules: Optional[Collection[str]] = None,
    exclude_rules: Collection[str] = (),
) -> MigrationResult:
    """
    Convert one flytekit (v1) file to flyte (v2) source code. Nothing is written to disk.

    Raises:
        MigrationError: the file cannot be read or parsed, or the generated code is invalid.
    """
    selected = select_rules(rules, exclude_rules)
    output_path = output_path_for(source_path, suffix)
    if source_path.suffix != ".py":
        raise MigrationError(f"{source_path} is not a Python file.")
    try:
        source = source_path.read_text()
    except (OSError, UnicodeDecodeError) as e:
        raise MigrationError(f"Cannot read {source_path}: {e}") from e

    if GENERATED_MARKER in "\n".join(source.splitlines()[:3]):
        return MigrationResult(source_path, output_path, "nothing_to_migrate")
    try:
        module = cst.parse_module(source)
    except cst.ParserSyntaxError as e:
        raise MigrationError(f"{source_path}:{e.editor_line}:{e.editor_column}: syntax error") from e
    if not _imports_flytekit(module):
        return MigrationResult(source_path, output_path, "nothing_to_migrate")

    ctx = MigrationContext(source_path=source_path, suffix=suffix)
    analyze(module, ctx)
    for rule in selected:
        module = rule(ctx).run(module)
    module = LeftoversRule(ctx).run(module)
    module = finalize_imports(module, ctx)
    if ctx.module_todos:
        module = module.with_changes(
            header=[*module.header, *(todo_comment(t) for t in dict.fromkeys(ctx.module_todos))]
        )

    code = _format(_with_header(module.code, source_path), output_path)
    try:
        cst.parse_module(code)
    except cst.ParserSyntaxError as e:
        raise MigrationError(
            f"Internal error: the generated code for {source_path} does not parse ({e.message})."
        ) from e

    todos = [
        Todo(line=number, message=line.split(TODO_MARKER, 1)[1].strip())
        for number, line in enumerate(code.splitlines(), start=1)
        if line.lstrip().startswith("#") and TODO_MARKER in line
    ]
    return MigrationResult(
        source_path=source_path,
        output_path=output_path,
        status="converted_with_todos" if todos else "converted",
        code=code,
        applied=ctx.applied,
        todos=todos,
        environments=ctx.environments,
    )


def _imports_flytekit(module: cst.Module) -> bool:
    for node in m.findall(module, m.ImportFrom() | m.Import()):
        if isinstance(node, cst.ImportFrom):
            names = [cst.Module([]).code_for_node(node.module)] if node.module is not None and not node.relative else []
        elif isinstance(node, cst.Import):
            names = [cst.Module([]).code_for_node(alias.name) for alias in node.names]
        else:
            continue
        if any(n == "flytekit" or n.startswith("flytekit.") for n in names):
            return True
    return False


def _with_header(code: str, source_path: Path) -> str:
    import flyte

    header = (
        f"{GENERATED_MARKER} (flyte {flyte.__version__}) from {source_path.name}.\n"
        f"# Review every `{TODO_MARKER.rstrip(':')}` marker before running this file.\n"
    )
    if code.startswith("#!"):
        shebang, _, rest = code.partition("\n")
        return f"{shebang}\n{header}{rest}"
    return header + code


def _format(code: str, output_path: Path) -> str:
    """Sort imports and format with ruff when it is installed. Formatting is best-effort."""
    ruff = _ruff_binary()
    if ruff is None:
        return code
    for args in (["check", "--select", "I", "--fix", "--quiet", "--exit-zero"], ["format", "--quiet"]):
        try:
            completed = subprocess.run(
                [ruff, *args, "--stdin-filename", str(output_path), "-"],
                input=code,
                capture_output=True,
                text=True,
                timeout=30,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired):
            return code
        if completed.returncode != 0 or not completed.stdout:
            return code
        code = completed.stdout
    return code


def _ruff_binary() -> Optional[str]:
    try:
        from ruff.__main__ import find_ruff_bin

        return find_ruff_bin()
    except (ImportError, FileNotFoundError):
        return shutil.which("ruff")
