[project]
name = "my-lib"
version = "0.1.0"
description = "My lib"
requires-python = ">=3.10"
dependencies = ["numpy"]

# This section needs to be added to get uv sync to install this package (this package being seeds).
[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["my_lib"]
