"""Resolving a run's profile from its name. There is no search -- see `_resolve`."""

from __future__ import annotations

import pathlib

import pytest

from flyteplugins.routing import resolve_run_profile
from flyteplugins.routing._tags import make_run_name

_CONFIG = """
task:
  project: shared
  domain: development
profiles:
  us-east:
    task: {project: east-proj}
  eu-west:
    task: {project: west-proj}
  gpu-pool:
    task: {project: gpu-proj}
"""


@pytest.fixture
def cfg_file(tmp_path: pathlib.Path) -> pathlib.Path:
    p = tmp_path / "config.yaml"
    p.write_text(_CONFIG)
    return p


def test_a_tagged_name_resolves(cfg_file: pathlib.Path) -> None:
    assert resolve_run_profile(make_run_name("gpu-pool"), cfg_file) == "gpu-pool"


@pytest.mark.parametrize("profile", ["us-east", "eu-west", "gpu-pool"])
def test_every_profile_round_trips(cfg_file: pathlib.Path, profile: str) -> None:
    assert resolve_run_profile(make_run_name(profile), cfg_file) == profile


def test_resolution_makes_no_network_calls(cfg_file: pathlib.Path, monkeypatch) -> None:
    """Decoding is pure string work. Nothing here may reach for a client."""
    import flyte

    def boom(*a, **kw):
        raise AssertionError("resolution must not build a client")

    monkeypatch.setattr(flyte, "use_profile", boom)
    monkeypatch.setattr(flyte, "aio_use_profile", boom)
    assert resolve_run_profile(make_run_name("us-east"), cfg_file) == "us-east"


@pytest.mark.parametrize(
    "name",
    [
        "somecontrolplanename",  # generated by the platform
        "my-own-name",  # chosen by the user
        "",  # nothing at all
        "toolongtag-abc",  # not our shape
    ],
)
def test_a_name_we_did_not_mint_uses_the_default(cfg_file: pathlib.Path, name: str) -> None:
    """None means "leave the ambient profile alone" -- the config file's default. Searching every
    cluster for the run would cost a round trip per profile on every lookup."""
    assert resolve_run_profile(name, cfg_file) is None


def test_a_tag_for_a_removed_profile_uses_the_default(cfg_file: pathlib.Path) -> None:
    name = make_run_name("a-profile-no-longer-in-this-config")
    assert resolve_run_profile(name, cfg_file) is None


def test_a_colliding_tag_uses_the_default(cfg_file: pathlib.Path, monkeypatch) -> None:
    """With no search to disambiguate, picking one at random and reporting it confidently is
    worse than falling back to the default."""
    import flyteplugins.routing._resolve as resolve_mod

    monkeypatch.setattr(resolve_mod, "profiles_for_tag", lambda tag, profiles: ["us-east", "eu-west"])
    assert resolve_run_profile(make_run_name("us-east"), cfg_file) is None


def test_config_without_profiles(tmp_path: pathlib.Path) -> None:
    p = tmp_path / "config.yaml"
    p.write_text("task:\n  project: shared\n")
    assert resolve_run_profile("anything", p) is None
