"""
Run a task that produces an HTML report, then pull the report back to the client and
write it to a local file.

The task enables reports with ``@env.task(report=True)`` and writes HTML into the report
using ``flyte.report``. After the run finishes, ``run.get_report()`` asks the data proxy for a
signed download link for the report artifact, downloads it, and returns the HTML as a string.
"""

import os
from pathlib import Path

import flyte
import flyte.report

env = flyte.TaskEnvironment(
    name="get-report-env",
    resources=flyte.Resources(memory="500Mi", cpu=1),
    image=flyte.Image.from_debian_base(),
)


@env.task(report=True)
async def make_report(name: str) -> str:
    """Write a small HTML report and return a greeting."""
    tab = flyte.report.get_tab("Greeting")
    tab.log(f"<h1>Hello, {name}!</h1>")
    tab.log("<p>This report was generated by a Flyte task.</p>")
    await flyte.report.flush.aio()
    return f"Hello, {name}!"


if __name__ == "__main__":
    flyte.init_from_config(os.environ.get("FLYTE_CONFIG"))

    run = flyte.run(make_report, name="world")
    print(f"Execution URL: {run.url}")

    # Block until the run reaches a terminal state so the report has been flushed to storage.
    run.wait()

    # Pull the report HTML back to the client and write it to a local file.
    report_html = run.get_report()
    output_path = Path("report.html")
    output_path.write_text(report_html)
    print(f"Report written to {output_path.resolve()}")
