[tool.uv.workspace]
members = ["bird_feeder", "seeds"]


[tool.uv.sources]
bird-feeder = { workspace = true }
seeds = { workspace = true }

[dependency-groups]
albatross = [
    "bird-feeder",
    "seeds",
    "numpy"
]