"""Free-form bash — pipes, redirects, here-docs, ``&&``, ``awk`` one-liners.

The script template is a real bash body. You can pipe between tools,
chain with ``&&`` / ``||``, redirect into named outputs,
embed ``awk`` or ``sed`` one-liners — anything bash can parse.

Run locally::

    uv run python 06_shell_features.py
"""

import sys
import tempfile
from pathlib import Path

import flyte
from flyte._image import PythonWheels
from flyte.extras import shell
from flyte.extras.shell import Stdout
from flyte.io import File

# Pipe chain + named-file output. Sort a file, dedupe, write to OutFile;
# count of unique lines comes out on stdout.
sort_unique = shell.create(
    name="sort_unique",
    image="debian:12-slim",
    inputs={"src": File},
    outputs={
        "sorted_unique": File,
        "unique_count": Stdout(type=int),
    },
    script=r"""
        sort {inputs.src} | uniq | tee {outputs.sorted_unique} | wc -l
    """,
)


# Conditional shell logic with a primitive output for the verdict.
sanity_check = shell.create(
    name="sanity_check",
    image="debian:12-slim",
    inputs={"src": File, "min_lines": int},
    outputs={
        "verdict": str,
    },
    # Note: don't wrap {inputs.x} in your own "..." — the wrapper already
    # emits scalar refs as `"${_VAL_X}"` (quoted). Double-quoting breaks
    # the outer quoting and re-enables word splitting on the value.
    script=r"""
        # Three-part chain: count lines, compare, emit verdict.
        n=$(wc -l < {inputs.src})
        if [ "$n" -ge {inputs.min_lines} ]; then
            echo "ok ($n lines)" > {outputs.verdict}
        else
            echo "too short ($n < {inputs.min_lines})" > {outputs.verdict}
        fi
    """,
)


# `awk` one-liner — compute a stat. Note double-braces escape `{` inside the
# Python f-string-like template (the script is a Python raw string).
mean_field = shell.create(
    name="mean_of_first_field",
    image="debian:12-slim",
    inputs={"src": File},
    outputs={"mean": Stdout(type=float)},
    script=r"""
        awk '{{ sum += $1; n += 1 }} END {{ if (n > 0) print sum/n; else print 0 }}' \
            {inputs.src}
    """,
)


# Here-doc: emit a multi-line report file from inputs.
report_summary = shell.create(
    name="report_summary",
    image="debian:12-slim",
    inputs={"title": str, "lines": int},
    outputs={"report": File},
    script=r"""
        cat > {outputs.report} <<EOF
# {inputs.title}

Total lines processed: {inputs.lines}
Generated by flyte shell task.
EOF
    """,
)


env = flyte.TaskEnvironment(
    name="shell_features",
    depends_on=[sort_unique.env, sanity_check.env, mean_field.env, report_summary.env],
    image=(
        flyte.Image.from_debian_base().clone(
            addl_layer=PythonWheels(
                wheel_dir=Path(__file__).parent.parent.parent / "dist",
                package_name="flyte",
            ),
            name="shell-basic",
        )
    ),
)


@env.task
async def features_demo(src: File, numbers: File) -> tuple[File, int, str, float, File]:
    sorted_file, n_unique = await sort_unique(src=src)
    verdict = await sanity_check(src=src, min_lines=3)
    mean = await mean_field(src=numbers)
    report = await report_summary(title="features demo", lines=n_unique)
    return sorted_file, n_unique, verdict, mean, report


if __name__ == "__main__":
    flyte.init_from_config()
    mode = "remote" if (len(sys.argv) > 1 and sys.argv[1] == "remote") else "local"

    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        f.write("delta\nalpha\nalpha\nbravo\ncharlie\nbravo\n")
        src_path = f.name
    with tempfile.NamedTemporaryFile(mode="w", suffix=".tsv", delete=False) as f:
        # Numbers in column 1, awk's $1.
        f.write("\n".join(str(i) for i in [3, 7, 11, 4, 9, 14, 5]))
        num_path = f.name

    run = flyte.with_runcontext(mode=mode).run(
        features_demo,
        File.from_local_sync(src_path),
        File.from_local_sync(num_path),
    )
    print(run.url if mode == "remote" else run)
    print(f"Output: {run.outputs()}")
