"""Write to Notion from Flyte tasks.

This example shows the basic client surface: creating a row in a database
with typed properties, creating a child page with content blocks, and
appending blocks to an existing page.

Requirements:
    pip install flyteplugins-notion

Setup:
    flyte create secret NOTION_TOKEN --value ntn_...

    Share the target database/page with your integration (page → ... →
    Connections).

Usage:
    python plugins/notion/examples/write_to_notion.py
"""

import flyte

from flyteplugins.notion import (
    NotionClient,
    heading_block,
    paragraph_block,
    select_property,
    title_property,
)

image = flyte.Image.from_debian_base(python_version=(3, 12)).with_pip_packages("flyteplugins-notion")

env = flyte.TaskEnvironment(
    name="notion-write",
    image=image,
    secrets=[flyte.Secret("NOTION_TOKEN", as_env_var="NOTION_TOKEN")],
)


@env.task
async def add_row(database_id: str, name: str, status: str) -> str:
    """Create a row (page) in a database and return its URL.

    The database needs properties named `Name` (title) and `Status` (select)
    with the given option.
    """
    async with NotionClient() as client:
        page = await client.create_database_page.aio(
            database_id,
            {"Name": title_property(name), "Status": select_property(status)},
        )
    return page["url"]


@env.task
async def write_report(parent_page_id: str, title: str, summary: str) -> str:
    """Create a child page containing a heading and a summary paragraph."""
    async with NotionClient() as client:
        page = await client.create_page.aio(
            parent_page_id,
            title=title,
            blocks=[heading_block(title, level=1), paragraph_block(summary)],
        )
        await client.append_blocks.aio(page["id"], [paragraph_block("Generated by Flyte.")])
    return page["url"]


if __name__ == "__main__":
    # Replace with ids shared with your integration.
    flyte.run(add_row, database_id="DATABASE_ID", name="Test row", status="Not started")
