"""Tests for the flytekit (v1) -> flyte (v2) source migration behind `flyte migrate`."""

import importlib.util
import textwrap
from pathlib import Path

import pytest

pytest.importorskip("libcst")

import flyte
from flyte._migrate import MigrationError, migrate_file, output_path_for


@pytest.fixture(autouse=True)
def no_ruff(monkeypatch):
    """Assert on the converter's own output; ruff formatting is best-effort and version dependent."""
    monkeypatch.setattr("flyte._migrate._migrate._ruff_binary", lambda: None)


def migrate(tmp_path: Path, source: str, name: str = "pipeline.py", **kwargs):
    path = tmp_path / name
    path.write_text(textwrap.dedent(source))
    return migrate_file(path, **kwargs)


def flat(code: str) -> str:
    return " ".join(code.split())


# -- file handling ------------------------------------------------------------------------------------------------


def test_output_path_uses_suffix_next_to_source():
    assert output_path_for(Path("workflows/pipeline.py")) == Path("workflows/pipeline_v2.py")
    assert output_path_for(Path("train.py"), "_flyte2") == Path("train_flyte2.py")


@pytest.mark.parametrize("suffix", ["", "-v2", ".v2", "_v 2"])
def test_invalid_suffix_is_rejected(suffix):
    with pytest.raises(MigrationError, match="Invalid suffix"):
        output_path_for(Path("pipeline.py"), suffix)


def test_file_without_flytekit_has_nothing_to_migrate(tmp_path):
    result = migrate(tmp_path, "import os\n")
    assert result.status == "nothing_to_migrate"
    assert result.code == ""


def test_generated_file_has_nothing_to_migrate(tmp_path):
    first = migrate(tmp_path, "from flytekit import task\n\n@task\ndef t() -> int:\n    return 1\n")
    first.output_path.write_text(first.code)
    assert migrate_file(first.output_path).status == "nothing_to_migrate"


def test_syntax_error_raises(tmp_path):
    with pytest.raises(MigrationError, match=r"pipeline.py:2:\d+: syntax error"):
        migrate(tmp_path, "from flytekit import task\ndef (:\n")


def test_unknown_rule_raises(tmp_path):
    with pytest.raises(MigrationError, match="Unknown rule"):
        migrate(tmp_path, "from flytekit import task\n", rules=["nope"])


def test_header_and_todo_line_numbers(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import conditional, task, workflow

        @task
        def t(x: int) -> int:
            return x

        @workflow
        def wf(x: int) -> int:
            return conditional("c").if_(x > 1).then(t(x=x)).else_().then(t(x=0))
        """,
    )
    lines = result.code.splitlines()
    assert lines[0].startswith("# Generated by `flyte migrate`")
    assert result.status == "converted_with_todos"
    assert [t.message for t in result.todos] == [
        "conditional() has no v2 equivalent; rewrite it as a Python if/elif/else inside the task"
    ]
    assert "TODO(flyte migrate)" in lines[result.todos[0].line - 1]


# -- tasks and environments ---------------------------------------------------------------------------------------


def test_single_environment_is_named_after_the_file(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import task

        @task(cache=True, cache_version="1", retries=3)
        def t(x: int) -> int:
            return x
        """,
    )
    code = flat(result.code)
    assert 'env = flyte.TaskEnvironment(name="pipeline_env")' in code
    assert '@env.task(cache=flyte.Cache(behavior="auto", version_override="1"), retries=3)' in code
    assert "flytekit" not in result.code
    assert result.environments == ["pipeline_env"]
    assert result.status == "converted"


def test_container_configuration_moves_to_grouped_environments(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import Resources, Secret, task, workflow
        from flytekit.extras.accelerators import T4

        @task(requests=Resources(cpu="1", mem="1Gi"), limits=Resources(cpu="2", mem="1Gi"))
        def a(x: int) -> int:
            return x

        @task(requests=Resources(cpu="1", mem="1Gi"), limits=Resources(cpu="2", mem="1Gi"))
        def b(x: int) -> int:
            return x

        @task(
            requests=Resources(gpu="1"),
            accelerator=T4,
            shared_memory=True,
            secret_requests=[Secret(group="g", key="k")],
        )
        def gpu(x: int) -> int:
            return x

        @workflow
        def wf(x: int) -> int:
            return b(x=a(x=x))
        """,
    )
    code = flat(result.code)
    assert (
        'pipeline_a_env = flyte.TaskEnvironment(name="pipeline_a_env", '
        'resources=flyte.Resources(cpu=("1", "2"), memory="1Gi"))' in code
    )
    assert (
        'pipeline_gpu_env = flyte.TaskEnvironment(name="pipeline_gpu_env", '
        "resources=flyte.Resources(gpu='T4:1', shm=\"auto\"), "
        'secrets=[flyte.Secret(key="k", group="g")])' in code
    )
    # Only environments whose tasks are actually called become dependencies.
    assert 'pipeline_env = flyte.TaskEnvironment(name="pipeline_env", depends_on=[pipeline_a_env])' in code
    assert "@pipeline_a_env.task def a(" in code
    assert "@pipeline_a_env.task def b(" in code
    assert "@pipeline_env.task(entrypoint=True) def wf(" in code
    # Environments that orchestrate other environments are defined last.
    assert code.index("pipeline_env = ") > code.index("pipeline_gpu_env = ")


def test_environments_are_defined_after_their_dependencies(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import dynamic, task, workflow

        @task(container_image="train:1")
        def train(x: int) -> int:
            return x

        @dynamic(container_image="sweep:1")
        def sweep(x: int) -> int:
            return train(x=x)

        @workflow
        def wf(x: int) -> int:
            return sweep(x=x)
        """,
    )
    code = flat(result.code)
    assert (
        'pipeline_sweep_env = flyte.TaskEnvironment(name="pipeline_sweep_env", image="sweep:1", '
        "depends_on=[pipeline_train_env])" in code
    )
    assert 'pipeline_env = flyte.TaskEnvironment(name="pipeline_env", depends_on=[pipeline_sweep_env])' in code
    assert code.index("pipeline_train_env = ") < code.index("pipeline_sweep_env = ") < code.index("pipeline_env = ")


def test_environment_dependency_cycle_uses_add_dependency(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import dynamic

        @dynamic(container_image="a:1")
        def a(x: int) -> int:
            return b(x=x)

        @dynamic(container_image="b:1")
        def b(x: int) -> int:
            return a(x=x)
        """,
    )
    code = flat(result.code)
    assert 'pipeline_a_env = flyte.TaskEnvironment(name="pipeline_a_env", image="a:1")' in code
    assert "depends_on=[pipeline_a_env])" in code
    assert "pipeline_a_env.add_dependency(pipeline_b_env)" in code


def test_dropped_task_arguments_leave_todos(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import task

        @task(labels={"team": "ml"}, deprecated="use t2")
        def t() -> int:
            return 1
        """,
    )
    assert {t.message for t in result.todos} == {
        "labels are set per run in v2; use flyte.with_runcontext(labels=...)",
        "`deprecated` has no v2 equivalent and was dropped",
    }


def test_module_alias_import_is_resolved(tmp_path):
    result = migrate(
        tmp_path,
        """
        import flytekit as fl

        @fl.task(requests=fl.Resources(mem="2Gi"))
        def t() -> int:
            return 1
        """,
    )
    code = flat(result.code)
    assert 'env = flyte.TaskEnvironment(name="pipeline_env", resources=flyte.Resources(memory="2Gi"))' in code
    assert "import flytekit" not in result.code


# -- workflows ----------------------------------------------------------------------------------------------------


PARALLEL_WORKFLOW = """
from typing import List

from flytekit import map_task, task, workflow


@task
def load(n: int) -> int:
    return n


@task
def square(x: int) -> int:
    return x * x


@task
def total(a: int, b: int, squares: List[int]) -> int:
    return a + b + sum(squares)


@workflow
def wf(n: int = 3) -> int:
    \"\"\"Independent calls run concurrently in v1.\"\"\"
    a = load(n=n)
    b = load(n=n + 1).with_overrides(retries=2)
    squares = map_task(square, concurrency=2)(x=[1, 2, 3])
    return total(a=a, b=b, squares=squares)


@workflow
def linear(n: int = 2) -> int:
    a = load(n=n)
    return square(x=a)
"""


def test_independent_workflow_calls_are_gathered(tmp_path):
    result = migrate(tmp_path, PARALLEL_WORKFLOW, name="parallel_wf.py")
    code = flat(result.code)
    assert "async def wf(n: int = 3) -> int:" in code
    assert (
        "a, b, squares = await asyncio.gather(load.aio(n=n), load.override(retries=2).aio(n=n + 1), "
        "_collect(flyte.map.aio(square, [1, 2, 3], concurrency=2, return_exceptions=False)))" in code
    )
    assert "return await total.aio(a=a, b=b, squares=squares)" in code
    assert "async def _collect(results):" in code
    assert '"""Independent calls run concurrently in v1."""' in code
    # A chain of dependent calls keeps its synchronous form.
    assert "def linear(n: int = 2) -> int: a = load(n=n) return square(x=a)" in code
    assert result.todos == []


def test_migrated_workflows_run_locally(tmp_path, monkeypatch):
    result = migrate(tmp_path, PARALLEL_WORKFLOW, name="parallel_run_wf.py")
    result.output_path.write_text(result.code)
    monkeypatch.syspath_prepend(str(tmp_path))
    spec = importlib.util.spec_from_file_location("parallel_run_wf_v2", result.output_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    flyte.init()
    assert flyte.with_runcontext(mode="local").run(module.wf, n=3).outputs()[0] == 3 + 4 + 1 + 4 + 9
    assert flyte.with_runcontext(mode="local").run(module.linear, n=2).outputs()[0] == 4


def test_ordering_operator_is_respected(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import task, workflow

        @task
        def a() -> None: ...

        @task
        def b() -> None: ...

        @task
        def c() -> None: ...

        @workflow
        def wf():
            x = a()
            y = b()
            z = c()
            x >> y
        """,
    )
    code = flat(result.code)
    assert "x, z = await asyncio.gather(a.aio(), c.aio()) y = await b.aio()" in code
    assert ">>" not in code


def test_unanalyzable_workflow_keeps_sequential_body_with_todo(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import task, workflow

        @task
        def t(x: int) -> int:
            return x

        @workflow
        def wf() -> int:
            a = t(x=1)
            b = t(x=t(x=2))
            return a
        """,
    )
    assert "async def" not in result.code
    assert [t.message for t in result.todos] == [
        "this workflow body could not be analyzed, so its calls run sequentially in v2; "
        "run independent calls concurrently with asyncio.gather"
    ]


# -- launch plans -------------------------------------------------------------------------------------------------


def test_scheduled_launch_plan_becomes_trigger(tmp_path):
    result = migrate(
        tmp_path,
        """
        from datetime import timedelta
        from flytekit import CronSchedule, FixedRate, LaunchPlan, task, workflow

        @task
        def t(n: int) -> int:
            return n

        @workflow
        def wf(n: int, kickoff: str) -> int:
            return t(n=n)

        LaunchPlan.get_or_create(
            workflow=wf,
            name="nightly",
            schedule=CronSchedule(schedule="0 0 * * *", kickoff_time_input_arg="kickoff"),
            default_inputs={"n": 1},
        )
        hourly = LaunchPlan.create("hourly", wf, schedule=FixedRate(duration=timedelta(hours=1)))
        """,
    )
    code = flat(result.code)
    assert (
        '@env.task(entrypoint=True, triggers=(flyte.Trigger(name="nightly", automation=flyte.Cron("0 0 * * *"), '
        'inputs={"n": 1, \'kickoff\': flyte.TriggerTime}), flyte.Trigger(name="hourly", '
        "automation=flyte.FixedRate(interval_minutes=60)),))" in code
    )
    assert "LaunchPlan" not in result.code
    assert result.todos == []


def test_unscheduled_launch_plan_is_kept_with_todo(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import LaunchPlan, task

        @task
        def t() -> int:
            return 1

        lp = LaunchPlan.get_or_create(workflow=t, name="adhoc")
        """,
    )
    assert "lp = LaunchPlan.get_or_create" in result.code
    assert "from flytekit import LaunchPlan" in result.code
    assert [t.message for t in result.todos] == [
        "LaunchPlans without a schedule have no v2 equivalent; pass inputs with flyte.with_runcontext or wrap the task"
    ]


# -- symbols, images and calls ------------------------------------------------------------------------------------


def test_symbols_are_renamed(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import current_context, task
        from flytekit.types.directory import FlyteDirectory
        from flytekit.types.file import FlyteFile

        @task
        def t(d: FlyteDirectory) -> FlyteFile:
            ctx = current_context()
            return FlyteFile("model.pkl")
        """,
    )
    code = flat(result.code)
    assert "from flyte.io import Dir, File" in code or ("from flyte.io import Dir" in code and "import File" in code)
    assert "def t(d: Dir) -> File:" in code
    assert "ctx = flyte.ctx()" in code
    assert 'return File.from_local_sync("model.pkl")' in code
    assert not [line for line in result.code.splitlines() if line.startswith(("import flytekit", "from flytekit"))]
    assert len(result.todos) == 1 and result.todos[0].message.startswith("flyte.ctx() returns a TaskContext")


def test_image_spec_becomes_image_builder(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import ImageSpec, task

        img = ImageSpec(python_version="3.11", packages=["pandas"], apt_packages=["git"], env={"A": "1"})

        @task(container_image=img)
        def t() -> int:
            return 1
        """,
    )
    code = flat(result.code)
    assert (
        'img = flyte.Image.from_debian_base(python_version=(3, 11)).with_apt_packages("git")'
        '.with_pip_packages("pandas").with_env_vars({"A": "1"})' in code
    )
    assert 'env = flyte.TaskEnvironment(name="pipeline_env", image=img)' in code


def test_dynamic_map_task_and_overrides_in_sync_code(tmp_path):
    result = migrate(
        tmp_path,
        """
        import functools
        from flytekit import Resources, dynamic, map_task, task

        @task
        def add(x: int, y: int) -> int:
            return x + y

        @dynamic
        def fan(xs: list[int]) -> list[int]:
            doubled = map_task(functools.partial(add, y=1), min_success_ratio=0.5)(x=xs)
            add(x=1, y=2).with_overrides(requests=Resources(cpu="2"), node_name="n")
            return doubled
        """,
    )
    code = flat(result.code)
    assert "doubled = list(flyte.map(functools.partial(add, y=1), xs, return_exceptions=True))" in code
    assert 'add.override(resources=flyte.Resources(cpu="2"), short_name="n")(x=1, y=2)' in code
    assert [t.message for t in result.todos] == [
        "failed map items are returned as exceptions in v2; filter them to honor min_success(es/_ratio)"
    ]


def test_eager_awaits_call_tasks_through_aio(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import eager, task

        @task
        def t(x: int) -> int:
            return x

        @eager
        async def main(x: int) -> int:
            return await t(x=x)
        """,
    )
    assert "return await t.aio(x=x)" in result.code
    assert "@env.task\nasync def main" in result.code


def test_local_flytekit_import_gets_todo_and_aio(tmp_path):
    (tmp_path / "tasks.py").write_text("from flytekit import task\n\n@task\ndef shared(x: int) -> int:\n    return x\n")
    result = migrate(
        tmp_path,
        """
        from flytekit import eager
        from tasks import shared

        @eager
        async def main(x: int) -> int:
            return await shared(x=x)
        """,
    )
    assert "return await shared.aio(x=x)" in result.code
    assert [t.message for t in result.todos] == [
        "`tasks` still uses flytekit; run `flyte migrate tasks.py` and import from its `tasks_v2` module"
    ]


def test_excluded_rule_leaves_flytekit_usage_flagged(tmp_path):
    result = migrate(
        tmp_path,
        """
        from flytekit import task

        @task
        def t() -> int:
            return 1
        """,
        exclude_rules=["tasks"],
    )
    assert "from flytekit import task" in result.code
    assert [t.message for t in result.todos] == ["`flytekit.task` has no automatic v2 mapping"]
